// @ts-check
/**
 * Reads SUPABASE_URL and SUPABASE_ANON_KEY from environment variables
 * (or from a local .env file in development) and writes them into the
 * Angular environment files before the build runs.
 *
 * Usage:
 *   Local dev  → copy .env.example to .env and fill in your values
 *   CI/CD      → set SUPABASE_URL and SUPABASE_ANON_KEY as env vars in your platform
 */

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { createRequire } from 'module';

// Load .env if it exists (local dev only — never committed)
const require = createRequire(import.meta.url);
if (existsSync('.env')) {
  const dotenv = require('dotenv');
  dotenv.config();
}

const supabaseUrl = process.env['SUPABASE_URL'];
const supabaseAnonKey = process.env['SUPABASE_ANON_KEY'];

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Missing required environment variables:');
  if (!supabaseUrl) console.error('   - SUPABASE_URL');
  if (!supabaseAnonKey) console.error('   - SUPABASE_ANON_KEY');
  console.error('\nCopy .env.example to .env and fill in the values.');
  process.exit(1);
}

const template = (production = false) => `\
// ⚠️  Auto-generated by scripts/set-env.mjs — do NOT edit or commit.
export const environment = {
  production: ${production},
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
};
`;

mkdirSync('src/environments', { recursive: true });
writeFileSync('src/environments/environment.ts', template(false));
writeFileSync('src/environments/environment.prod.ts', template(true));

console.log('✅ Environment files generated successfully');
